# -*- coding: utf-8 -*-
"""BicycleModel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uAS86Mm5s3oCYoIhW1AE9ipZBK7GJHAV

# Bicycle Car Model Mathematical Modelling
"""

def BicycleCarModel(input,state):  #w8ing for the inputs (only steering angle) and states (longitudinal velocity, lateral velocity, yaw angle). Note that this model assumes NO ACCELEARTION!!!

  output = [None]*3 # size def

  lf = 40 # to be determined 
  lr = 25 # to be determined 
    
  vel = (state[0]**2+state[1]**2)**0.5

  output[0] = vel*math.cos(state[2]+math.atan((lr/(lf+lr))*math.tan(input)))  # xdot (horizontal velocity wrt absolute cartesian coord. system)
  output[1] = vel*math.sin(state[2]+math.atan((lr/(lf+lr))*math.tan(input)))  # ydot (vertical velocity wrt absolute cartesian coord. system)
  output[2] = (vel/lr)*math.sin(math.atan((lr/(lf+lr))*math.tan(input))) 
  
  
  

  return output